Update internal_manifest.json
Pathfinder-WOTR-Modding-Community/ModFinder pull request #89
Opened 2024-02-05 22:29 UTC by SlyDevil

Added my owlmod for Lich Decree Reductions to the internal manifest because why can a palace be built in 7 days but Zach's Pleasure Palace takes 30.

Probably did this right, but who knows.

2024-02-05 22:43 UTC, WittleWolfie requested changes

2024-02-05 22:43 UTC, WittleWolfie commented on ManifestUpdater/Resources/internal_manifest.json
> +        "Type": "OMM"
Type should be Owlcat

2024-02-06 03:26 UTC, SlyDevil commented on ManifestUpdater/Resources/internal_manifest.json
> +        "Type": "OMM"
Type is now Owlcat.

Not sure if it was possible to make the change on the original commit. Thought I was but apparently there's a 2nd commit now. Woops?

What does the listed type change? When doing a drag n' drop on modfinder, it recognizes the difference between UMM and owlcat implicitly, and extracts the zip to the correct folder (+ModManifest changes for Owlmods).

2024-02-06 22:41 UTC, WittleWolfie commented on ManifestUpdater/Resources/internal_manifest.json
> +        "Type": "OMM"
Great question I have no idea :P I don't remember.

2024-02-06 22:42 UTC, WittleWolfie approved these changes

2024-02-06 22:42 UTC, merged